dependencies:
  - autopep8==1.6.0
  - certifi==2021.10.8
  - charset-normalizer==2.0.7
  - click==8.0.3
  - idna==3.3
  - itsdangerous==2.0.1
  - Jinja2==3.0.2
  - MarkupSafe==2.0.1
  - numpy==1.21.3
  - openai==0.27.1
  - openpyxl==3.0.9
  - pandas==1.3.4
  - pandas-stubs==1.2.0.35
  - pycodestyle==2.8.0
  - python-dateutil==2.8.2
  - python-dotenv==0.19.2
  - pytz==2021.3
  - requests==2.26.0
  - six==1.16.0
  - tiktoken==0.4.0
  - toml==0.10.2
  - tqdm==4.62.3
  - urllib3==1.26.7
  - Werkzeug==2.0.2
  - reportlab==3.6.12
  - pip
  - pip:
    - aiofiles
    - configparser
    - et-xmlfile==1.1.0
    - langchain==0.0.129
    - Flask==2.1.1
    - Flask-PyMongo==2.3.0
    - Flask-Cors==3.0.10
    - Flask-Bcrypt==1.0.1
    - marshmallow==3.19.0
    - pyjwt==2.6.0
    - pymongo==4.3.3
    - squareup==28.0.1.20230608
    - uuid
